SCREENSIZE = 800,600
FILLCOLOR = 0,0,0   
BACKGROUNDIMAGE = "background.jpg"
GAMESTATE_RUN = 1
GAMESTATE_QUIT = 2
SCROLLSPEED = 100 #100 pixels per second
SCROLLWIDTH = 30 #width of border that makes it scroll
FRAMERATE = 15  #frame rate of all animations
DRAGDISTANCE = 4 #distance required to move mouse before it becomes a drag instead of a click
DRAGRECTCOLOR = 0,0,255
TURNSPEED = 90 #degrees per second
MOVESPEED = 50 #pixels per second basic move speed
HEALTHBARGAP = 15 #vertical position of health bar relative to the units rect
HEALTHBARSIZE = (60,5)
GRIDSIZE = 200  #size of a grid... this should never be below the sight distance, because a unit gets passed all units in the grid locations around itself but nothing further
BUTTONSPACING = 5 #space between GUI buttons
AVOIDDISTANCE = 50 # distance to begin avoid move at(in addition to the radiuses of each unit)
MINIMAPWIDTH = 150
MINIMAPHEIGHT = 150
MINIMAPSCALEX = 2
MINIMAPSCALEY = 2
MINIMAPDOTSIZE = 2
