SCREENSIZE = 800,600
FILLCOLOR = 0,0,0   
BACKGROUNDIMAGE = "background.jpg"
GAMESTATE_RUN = 1
GAMESTATE_QUIT = 2
SCROLLSPEED = 100 #100 pixels per second
SCROLLWIDTH = 30 #width of border that makes it scroll
FRAMERATE = 15  #frame rate of all animations
DRAGDISTANCE = 4 #distance required to move mouse before it becomes a drag instead of a click
DRAGRECTCOLOR = 0,0,255
TURNSPEED = 90 #degrees per second
MOVESPEED = 50 #pixels per second basic move speed
HEALTHBARGAP = 30 #vertical position of health bar relative to the units rect
HEALTHBARSIZE = (60,20)
